### ISSUE TITLE
Addon Verification

### ISSUE THREAD

**Issue by cqb13** [AntiCope/anticope.ml#16]
### Addon name

Numby Hack

### Description

A simple Meteor addon focused on giving users more customization options. Made in honor of Number81.

### Links

https://github.com/cqb13/Numby-hack

### Addon icon url

https://raw.githubusercontent.com/cqb13/Numby-hack/main/src/main/resources/assets/numby-hack/textures/icon.png
assets/numby-hack/textures/icon.png

### Authors

Me (cqb13)
Crosby

### Is your addon open-source?

- [X] Open-source

**Comment by C10udburst** [comment]
added in e8122741d1858c94a3d656c4cbe59b4f31988656
