### ISSUE TITLE
incompatibility with VINERY V1.20 and up

### ISSUE THREAD

**Issue by CloudyTiredDays** [AntiCope/anticope.ml#19]
<html>
<body>

[00:01:16] [main/WARN]: Error loading class: org/spongepowered/asm/synthetic/args/Args$3 (java.lang.ClassNotFoundException: org/spongepowered/asm/synthetic/args/Args$3)
--
642 | [00:01:17] [main/WARN]: @Final field field_6280:Ljava/util/Map; in vinery.mixins.json:LivingEntityMixin from mod vinery should be final
643 | [00:01:17] [main/WARN]: @Redirect conflict. Skipping vinery.mixins.json:LivingEntityMixin from mod vinery->@Redirect::improvedWaterBreathingSpeed(Lnet/minecraft/class_1309;Lnet/minecraft/class_1291;)Z with priority 1000, already redirected by meteor-client.mixins.json:LivingEntityMixin from mod meteor-client->@Redirect::travelHasStatusEffectProxy(Lnet/minecraft/class_1309;Lnet/minecraft/class_1291;)Z with priority 1000
644 | [00:01:17] [main/ERROR]: Minecraft has crashed!

</body>
</html>

**Comment by Weigurde** [comment]
go make an issue in the meteor github repo, not here
