### ISSUE TITLE
Cant open anticope.ml

### ISSUE THREAD

**Issue by afekushi** [AntiCope/anticope.ml#20]
When i go to "https://anticope.ml/"
i get a "This Site Cant Be Reached error"
![image](https://github.com/AntiCope/anticope.ml/assets/90076856/082a6cdb-e942-43ed-bdca-5c4f5126435c)

**Comment by Geming400** [comment]
High chance that the site was taken down.

**Comment by CrytoPal** [comment]
Look in the discord, there's an alternative link there

**Comment by hXR16F** [comment]
[.ml domains are down](https://www.reddit.com/r/freenom/comments/154c1x8/ml_domains_are_getting_taken_down_and_no_longer/)

**Comment by Aholicknight** [comment]
> Look in the discord, there's an alternative link there

@CrytoPal whats the new url?

**Comment by crosby-moe** [comment]
> > Look in the discord, there's an alternative link there
> 
> @CrytoPal whats the new url?

https://anticope.pages.dev/
